name: fase_2_consumo_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  http: ^1.6.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^9.1.1
  meta: ^1.17.0
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
